//! Router-owned RetroArch hotkey fragments (Phase 8b).
//!
//! Never writes the user's `retroarch.cfg`. Fragments live under app data and
//! are applied only via `--appendconfig` at launch (SPEC.md §8.1 / §20.2).

use std::path::{Path, PathBuf};

use sqlx::SqlitePool;

use crate::db::{self, hotkeys as hotkeys_db};
use crate::error::{AppError, AppResult};
use crate::model::{HotkeyFragmentPreview, HotkeyProfile};

pub const FRAGMENT_FILE: &str = "router-hotkeys.cfg";

pub fn fragment_path(app_data_dir: &Path) -> PathBuf {
    app_data_dir.join(FRAGMENT_FILE)
}

/// Builds the RetroArch cfg text for exit hotkeys.
pub fn render_fragment(profile: &HotkeyProfile) -> String {
    let mut lines = vec![
        "# Generated by Aeonic Arcadia — do not edit by hand.".to_string(),
        "# Applied only via --appendconfig; never written into retroarch.cfg.".to_string(),
        "input_enable_hotkey = \"nul\"".to_string(),
        "input_exit_emulator = \"nul\"".to_string(),
    ];

    if let Some(btn) = profile.enable_btn {
        lines.push(format!("input_enable_hotkey_btn = \"{btn}\""));
    } else {
        lines.push("input_enable_hotkey_btn = \"nul\"".into());
    }
    if let Some(btn) = profile.exit_btn {
        lines.push(format!("input_exit_emulator_btn = \"{btn}\""));
    } else {
        lines.push("input_exit_emulator_btn = \"nul\"".into());
    }

    // Prevent RetroArch from writing this fragment into the user's main cfg
    // when config_save_on_exit is on in the append layer.
    lines.push("config_save_on_exit = \"false\"".into());
    lines.push(String::new());
    lines.join("\n")
}

pub async fn get_profile(pool: &SqlitePool) -> AppResult<HotkeyProfile> {
    hotkeys_db::get_default(pool).await
}

pub async fn set_binding(
    pool: &SqlitePool,
    exit_btn: Option<i64>,
    exit_btn_label: Option<String>,
    enable_btn: Option<i64>,
    enable_btn_label: Option<String>,
) -> AppResult<HotkeyProfile> {
    hotkeys_db::update_binding(
        pool,
        exit_btn,
        exit_btn_label.as_deref(),
        enable_btn,
        enable_btn_label.as_deref(),
    )
    .await
}

pub async fn set_enabled(pool: &SqlitePool, enabled: bool) -> AppResult<HotkeyProfile> {
    hotkeys_db::set_enabled(pool, enabled).await
}

pub async fn preview(
    pool: &SqlitePool,
    app_data_dir: &Path,
) -> AppResult<HotkeyFragmentPreview> {
    let profile = hotkeys_db::get_default(pool).await?;
    let content = render_fragment(&profile);
    let path = fragment_path(app_data_dir);
    let existing = if path.is_file() {
        std::fs::read_to_string(&path).unwrap_or_default()
    } else {
        String::new()
    };

    let config_path: Option<String> =
        db::settings::get(pool, "emulator.retroarchConfigPath").await?;
    let mut warnings = Vec::new();
    if let Some(cfg) = config_path.as_deref() {
        if let Ok(text) = std::fs::read_to_string(cfg) {
            if text.lines().any(|line| {
                let t = line.trim();
                t.starts_with("config_save_on_exit")
                    && (t.contains("\"true\"") || t.contains("= true"))
            }) {
                warnings.push(
                    "Your RetroArch config has config_save_on_exit = true. \
                     The Router fragment forces it false in the append layer, \
                     but confirm RetroArch does not rewrite your main cfg after exit."
                        .into(),
                );
            }
        }
    }
    if profile.exit_btn.is_none() {
        warnings.push("No exit button is assigned yet.".into());
    }

    Ok(HotkeyFragmentPreview {
        path: path.display().to_string(),
        content,
        existing_content: existing,
        warnings,
        profile,
    })
}

pub async fn apply(pool: &SqlitePool, app_data_dir: &Path) -> AppResult<HotkeyProfile> {
    let profile = hotkeys_db::get_default(pool).await?;
    if profile.exit_btn.is_none() {
        return Err(AppError::user(
            "Exit button not set",
            "Assign a controller button for Exit before applying the hotkey fragment.",
        ));
    }
    let path = fragment_path(app_data_dir);
    let content = render_fragment(&profile);
    std::fs::write(&path, content).map_err(|source| AppError::Filesystem {
        path: path.display().to_string(),
        source,
    })?;
    hotkeys_db::set_fragment_path(pool, &path.display().to_string(), false).await
}

pub async fn mark_verified(pool: &SqlitePool, verified: bool) -> AppResult<HotkeyProfile> {
    hotkeys_db::set_verified(pool, verified).await
}

/// Returns the fragment path when an enabled profile with a written fragment exists.
pub async fn appendconfig_for_launch(
    pool: &SqlitePool,
    app_data_dir: &Path,
) -> AppResult<Option<PathBuf>> {
    let profile = hotkeys_db::get_default(pool).await?;
    if !profile.enabled {
        return Ok(None);
    }
    let path = fragment_path(app_data_dir);
    if path.is_file() && profile.exit_btn.is_some() {
        Ok(Some(path))
    } else {
        Ok(None)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fragment_includes_exit_button_and_disables_config_save() {
        let profile = HotkeyProfile {
            id: 1,
            name: "Default".into(),
            enabled: true,
            exit_btn: Some(1),
            exit_btn_label: Some("B".into()),
            enable_btn: Some(8),
            enable_btn_label: Some("Select".into()),
            fragment_path: None,
            verified: false,
            updated_at: String::new(),
        };
        let text = render_fragment(&profile);
        assert!(text.contains("input_exit_emulator_btn = \"1\""));
        assert!(text.contains("input_enable_hotkey_btn = \"8\""));
        assert!(text.contains("config_save_on_exit = \"false\""));
    }
}
