//! Integration checks for hotkey fragments, local media, and save-state discovery.

use std::path::PathBuf;

use aeonic_arcadia_lib::emulator::{hotkeys, retro_cfg};
use aeonic_arcadia_lib::media::local;
use aeonic_arcadia_lib::model::{HotkeyProfile, MediaKind};

#[test]
fn hotkey_fragment_is_append_only_and_disables_config_save() {
    let profile = HotkeyProfile {
        id: 1,
        name: "Default".into(),
        enabled: true,
        exit_btn: Some(1),
        exit_btn_label: Some("B".into()),
        enable_btn: Some(8),
        enable_btn_label: Some("Select".into()),
        fragment_path: None,
        verified: false,
        updated_at: String::new(),
    };
    let text = hotkeys::render_fragment(&profile);
    assert!(text.contains("input_exit_emulator_btn = \"1\""));
    assert!(text.contains("config_save_on_exit = \"false\""));
    assert!(text.contains("Generated by Aeonic Arcadia"));
}

#[test]
fn local_media_resolves_set_name_under_kind_folder() {
    let root = tempfile::tempdir().unwrap();
    let box_dir = root.path().join("box");
    std::fs::create_dir_all(&box_dir).unwrap();
    let file = box_dir.join("pacman.png");
    std::fs::write(&file, b"png").unwrap();
    let found = local::find_asset(root.path(), &MediaKind::Box, &["pacman".into()]);
    assert_eq!(found.unwrap(), file);
}

#[test]
fn savestate_discovery_finds_slots_and_entry_files() {
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join("1942.state"), b"0").unwrap();
    std::fs::write(dir.path().join("1942.state3"), b"3").unwrap();
    std::fs::write(dir.path().join("1942.state3.png"), b"png").unwrap();
    std::fs::write(dir.path().join("1942.state5.entry"), b"e").unwrap();
    let found = retro_cfg::discover_slots(&[dir.path().to_path_buf()], "1942");
    assert!(found.iter().any(|(s, _, _, e)| *s == 0 && !*e));
    assert!(found
        .iter()
        .any(|(s, _, thumb, e)| *s == 3 && !*e && thumb.is_some()));
    assert!(found.iter().any(|(s, path, _, e)| {
        *s == 5 && *e && path.file_name().unwrap() == "1942.state5.entry"
    }));
}

#[test]
fn retro_cfg_parse_reads_savestate_directory() {
    let cfg = retro_cfg::parse_text(
        r#"
savestate_directory = "D:\States"
savestates_in_content_dir = "false"
"#,
    );
    assert_eq!(
        cfg.get_path("savestate_directory"),
        Some(PathBuf::from(r"D:\States"))
    );
}
